name: eventlogtester

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  buildruntest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get -y install libefivar-dev pylint python3-pip tpm2-tools
      - run: sudo pip3 install pyright yq

      # run pylint. WARNING this cannot fail at the moment.
      - name: Run pylint
        run: pylint --rcfile pylintrc eventlog/eventlog.py || true

      # run pyright. WARNING not set up to fail at the moment.
      - name: Run pyright
        run: pyright || true

      # run the test evaluator
      - name: Compare event log JSON with reference
        run: env PATH=${PATH}:`pwd`/testing testfun.sh testlogs/css-flex14vm4-bootlog.binary
