name: eventlogtester

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  buildruntest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -y install libefivar-dev pylint python3-pip tpm2-tools
      - run: sudo pip3 install pyright

      # run pylint
      - name: Run pylint
        run: |
          pylint --rcfile pylintrc eventlog.py
          true

      # run pyright
      - name: Run pyright
        run: |
          pyright
          true

      # run the test evaluator
      - name: Compare event log JSON with reference
        run: |
          export PATH=${PATH}:`pwd`/testing
          testfun.sh testlogs/css-flex14vm4-bootlog.binary
