name: eventlogtester

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  buildruntest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get -y install libefivar-dev pylint python3-pip tpm2-tools
      - run: sudo pip3 install pyright yq

      # run pylint. WARNING this cannot fail at the moment.
      - name: Run pylint
        run: pylint --rcfile pylintrc eventlog/eventlog.py

      # run pyright.
      - name: Run pyright
        run: pyright

      # run the test evaluator
      - name: Compare event log JSON with reference
        run: env PATH=${PATH}:${PWD}/testing test_compare.py -d ${PWD}/testlogs
